title: Sofia Soares, Ph.D. # your name (or website title) here
logo: "/images/soares_800x450.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a neuroscientist by training on a journey to use the power of data for positive impact. 
  <br>
  I have an extensive background working with large and varied datasets, from database creation and management to behavioral and time series analysis using advanced statistical, machine learning and AI tools. 

  <br><br>
  <a href="https://sofiasoares.github.io/about_me/">More about me</a> 
  <br><br>
  <a href="https:\\www.linkedin.com\in\sofialssoares\">LinkedIn</a> 
  <br><br>
  <a href="https://scholar.google.pt/citations?user=C5WXvbEAAAAJ&hl=en">Publications</a>
  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
